### ISSUE TITLE
Large image is missing from the final output

### ISSUE THREAD

**Issue by rniswonger** [web-design-weekly/basic-webpack#1]
After running webpack, the large image file is placed in the build folder but incorrectly referenced in the compiled script. I'm guessing this is a config issue with the url-loader or file-loader fallback but haven't solved it yet (I'm new to this).

**Comment by rniswonger** [comment]
Oh, I just needed to update the publicPath URL in webpack.config.js to include the build folder.

**Comment by jakebresnehan** [comment]
@rniswonger :+1:
